### ISSUE TITLE
Puzzles: Advent of Code 2019

### ISSUE THREAD

**Issue by Claude-Ray** [tt-up/fed-in-depth#5]
https://adventofcode.com/

Advent of Code 是一个为期 25天的编程挑战，从 12 月 1 日到 25 日，每天发布一道新题目。

亲测题目难度适中，可玩性较高，解题过程没有任何限制，只求各种花式操作。

2019 年的活动刚开展了不满一周，在 Reddit 论坛的热度很高。

我们也来刷这个游戏吧，一起交流解题思路！

**Comment by yuqingc** [comment]
尴尬。找半天没找打题在哪😳😳

**Comment by Claude-Ray** [comment]
@yuqingc 首页数字点进去是题目，登录之后就能看到输入框了

**Comment by yuqingc** [comment]
> 
> 
> @yuqingc 首页数字点进去是题目，登录之后就能看到输入框了

Got it

**Comment by Claude-Ray** [comment]
感觉题目设计不是特别好，而且今年活动已结束，我决定停更了（😄️做的太慢了……

**Comment by yuqingc** [comment]
> 感觉题目设计不是特别好，而且今年活动已结束，我决定停更了（smile做的太慢了……

🤣我还没看呢。都说不好了，那我感觉我可以不用看了哈哈
